feat: find tsserver from path
pmizio/typescript-tools.nvim pull request #163
Opened 2023-09-23 19:58 UTC by perrin4869

https://github.com/pmizio/typescript-tools.nvim/pull/152 introduced the ability to find `tsserver` based on `mason-registry`.
That approach is problematic because calling `require('mason-registry').get_package(...)` requires `require('mason-registry').refresh` to have been called first.
`mason` works by installing the LSPs into the path, unfortunately though, `tsserver` is just not available yet.
Once https://github.com/mason-org/mason-registry/pull/2845 goes through though, we can do `MasonInstall tsserver`, and voilla, no need to reach into the mason registry.
Leaving this as a draft until the registry PR goes in
@williamboman thanks for the help here!!!

2023-09-24 11:58 UTC, williamboman reviewed
It seems like typescript-tools.nvim launches the Node script directly (i.e. `node <path_to_tsserver.js>`). While this would work fine on Unix systems because the `tsserver` executable is already a Node script, it won't work on Windows because `tsserver` is a `.cmd` script.

I also believe providing tsserver via Mason will trip up the "global" detection that takes place earlier.

2023-09-25 00:42 UTC, perrin4869 commented
hm... it seems windows support is already there, don't think this PR would break it?
the global detection seems to try a provided absolute path, don't think it would be affected either?

2023-09-25 07:18 UTC, pmizio commented
Oh, this must be some race condition introduced code works for me and few other users. In fact this code was posted in someones issue about mason integration in this repo. But if it really is problematic than I really appreciate to solve this with you!

@williamboman Yes and no, we indeed spawn using `node <path>/tsserver.js` but we don't provide hashbanged script or cmd file for windows as node param. We use its path to determinate where main js file is so we walk out of `bin` dir and looking for it manually in `lib` directory like you see [here](https://github.com/pmizio/typescript-tools.nvim/blob/05dcc6dfc3fe032a3e12f05afff0c1bbe3d490be/lua/typescript-tools/tsserver_provider.lua#L58).

@perrin4869 If mason really put tsserver into PATH then you need to just delete all mason related code we have already typescritpt detection from PATH [here](https://github.com/pmizio/typescript-tools.nvim/blob/05dcc6dfc3fe032a3e12f05afff0c1bbe3d490be/lua/typescript-tools/tsserver_provider.lua#L58) and [here](https://github.com/pmizio/typescript-tools.nvim/blob/05dcc6dfc3fe032a3e12f05afff0c1bbe3d490be/lua/typescript-tools/tsserver_provider.lua#L156). So like I said if mason put tsserver in PATH everything should work out of the box.
But one thing I want to save is message for users which integrate mason via forcing path, maybe there is way to get general mason installation path instead of path specific to package? And use it to show warning message.

2023-09-25 07:58 UTC, perrin4869 commented
oh right, sorry, didn't notice that the `global_install_path` was using `exepath`, sorry about that 😅
I fixed this PR to execute `mason_registry.get_package("typescript-language-server")` only after the check for global `tsserver`. The reason for this, is that `mason_registry.get_package("typescript-language-server")` should really only be called after a `mason_registry.refresh()` call. In a regular `mason` setup, this will still work without the call (but afaik, it's not guaranteed to work in the future), but if you use the `file` `mason-registry` source, you'll encounter this error. You can try it as follows:

```lua
require("mason").setup({
	registries = {
		"file:" .. vim.fs.joinpath(vim.fn.stdpath("data"), "mason-registry"),
	},
})
```

And cloning `mason-registry`: 

```
git clone git@github.com:mason-org/mason-registry.git home/.local/share/nvim/mason-registry
```

The solution to this problem would be to wrap the call to `mason_registry.get_package` inside a callback to `mason_registry.refresh`, but that would make `TsserverProvider:get_executable_path` asynchronous...

2023-09-25 10:17 UTC, pmizio commented
I'm fine with this but there is problem if someone force mason tsserver using `tsserver_path` setting then this function returns early and user will not be notified about integration. We probably need to change logic of `tsserver_path` setting or workaround async stuff... It is doable because `tsserver_provider` now also has async component [here](https://github.com/pmizio/typescript-tools.nvim/blob/05dcc6dfc3fe032a3e12f05afff0c1bbe3d490be/lua/typescript-tools/tsserver_provider.lua#L62) but challange is to call `on_loaded` callback after all async events ends and remember someone can call plugin without mason.

2023-10-02 09:53 UTC, pmizio commented
@perrin4869 Can you go with @williamboman suggestion and I think we can finally merge this!

2023-10-02 10:41 UTC, perrin4869 commented
hm... do you have any idea what's causing the errors? I think `Path:new(vim.env.MASON, "packages", "typescript-language-server")` is causing an error

2023-10-02 11:06 UTC, pmizio commented
> hm... do you have any idea what's causing the errors? I think `Path:new(vim.env.MASON, "packages", "typescript-language-server")` is causing an error

Use `os.getenv("MASON")` instead of `vim.env.MASON` to get env variable form lua context not vim one.

2023-10-02 11:10 UTC, pmizio requested changes

2023-10-02 11:10 UTC, pmizio commented on lua/typescript-tools/tsserver_provider.lua
> +    tsserver_path = mason_tsserver:join("typescript", "lib", "tsserver.js")
I think it should be:
```suggestion
    tsserver_path = mason_tsserver:joinpath("typescript", "lib", "tsserver.js")
```

2023-10-02 11:16 UTC, pmizio requested changes

2023-10-02 11:16 UTC, pmizio commented on lua/typescript-tools/tsserver_provider.lua
> +  local MASON = os.getenv "MASON"
I swear one last thing! 😄
```suggestion
  local mason_path = os.getenv "MASON"
```

2023-10-02 11:18 UTC, perrin4869 commented on lua/typescript-tools/tsserver_provider.lua
> +  local MASON = os.getenv "MASON"
done 😄

2023-10-02 11:20 UTC, pmizio approved these changes
Ok, so I test this later and if everything is ok I will merge!

2023-10-02 12:24 UTC, merged

2023-10-02 12:42 UTC, perrin4869 commented
cool! Just [updated and tested](https://github.com/perrin4869/dotfiles/pull/2743) on my end, everything's golden now, thank you so much!